import {
  DEFAULT_EXPORT_DIMENSIONS,
  DEFAULT_FRAME_RATE,
  DEFAULT_PROJECT_DIMENSIONS,
  DEFAULT_PROJECT_DURATION_MS,
  VIDEO_PROJECT_SCHEMA_VERSION,
} from "./constants";
import type { VideoProject } from "./schema";

export function createDefaultVideoProject(
  overrides: Partial<VideoProject> = {},
): VideoProject {
  const now = new Date().toISOString();

  return {
    version: VIDEO_PROJECT_SCHEMA_VERSION,
    projectId: "",
    createdAt: now,
    updatedAt: now,
    meta: {
      name: "Untitled Project",
      description: null,
      presetId: null,
      source: "editor",
      tags: [],
    },
    timing: {
      durationMs: DEFAULT_PROJECT_DURATION_MS,
      fps: DEFAULT_FRAME_RATE,
      beatOffsetMs: 0,
    },
    viewport: {
      width: DEFAULT_PROJECT_DIMENSIONS.width,
      height: DEFAULT_PROJECT_DIMENSIONS.height,
      backgroundColor: "#000000",
      aspectRatio: "1:1",
    },
    audio: {
      assetId: null,
      source: null,
      analysisId: null,
      trimStartMs: 0,
      trimEndMs: null,
      gain: 1,
    },
    visualizer: {
      enabled: true,
      pipeline: "CircleWavePipeline",
      logoVisible: true,
      mediaSource: null,
      logoSource: null,
      waveCircles: [],
      waveType: "spectrum",
      layoutType: "default",
      reflectionType: "none",
      shakeAmount: "none",
      radiusFactor: 0,
      seperationFactor: 0,
      waveScaleFactor: 1,
      logoSizeFactor: 1,
      bounceFactor: 1,
      centerCutoutFactor: 0,
      delayed: false,
      inverted: false,
      waveStyle: "solid",
      barCount: 128,
      barWidth: 1,
      pointRadius: 1,
      smoothed: true,
      glowSettings: {
        enabled: false,
        glowType: "outer",
        blur: 0,
        scale: 1,
      },
      fireSettings: {
        enabled: false,
        intensity: 0,
        detail: 0,
      },
      dropShadowSettings: {
        enabled: false,
        color: "#000000",
        blur: 0,
        opacity: 1,
      },
      position: {
        x: 0,
        y: 0,
      },
      spinSettings: {
        enabled: false,
        speed: 0,
        acceleration: 0,
        logoLocked: false,
      },
      drift: {
        enabled: false,
        intensity: 0,
        customMode: false,
        amplitudeX: 0,
        amplitudeY: 0,
        rotation: 0,
        speed: 0,
        octaves: 1,
        scale: 1,
        acceleration: 0,
      },
      width: 0,
      baseHeight: 0,
      rotation: 0,
      shape: "circle",
      glowType: "outer",
    },
    backdrop: {
      source: null,
      bounceEnabled: false,
      bounceScale: 0,
      paddingFactor: 1,
      shakeEnabled: false,
      shakeFactor: 18,
      filterEnabled: false,
      rotation: 0,
      vignetteEnabled: false,
      maxVignette: 0,
      vignetteFactor: 0,
      contrastEnabled: false,
      maxContrast: 1,
      contrastFactor: 0,
      zoomBlurEnabled: false,
      maxZoomBlur: 0,
      zoomBlurFactor: 0,
      reflection: {
        type: "none",
        direction: "down",
      },
      hlsAdjustment: {
        enabled: false,
        colorize: false,
        alpha: 0,
        hue: 0,
        lightness: 0,
        saturation: 0,
      },
      drift: {
        enabled: false,
        intensity: 0,
        customMode: false,
        amplitudeX: 0,
        amplitudeY: 0,
        rotation: 0,
        speed: 0,
        octaves: 1,
        scale: 1,
        acceleration: 0,
      },
    },
    lyrics: {
      style: {
        text: "",
        color: "#ffffff",
        anchorPoint: "center",
        font: "Montserrat",
        fontSize: 48,
        bold: false,
        shadow: {
          enabled: false,
          color: "#000000",
          blur: 0,
          opacity: 1,
        },
        position: {
          x: 0,
          y: 0,
        },
        drift: {
          enabled: false,
          intensity: 0,
          customMode: false,
          amplitudeX: 0,
          amplitudeY: 0,
          rotation: 0,
          speed: 0,
          octaves: 1,
          scale: 1,
          acceleration: 0,
        },
      },
      segments: [],
    },
    textLayers: [],
    overlays: {
      particles: {
        enabled: false,
        speedUpEnabled: false,
        direction: "up",
        items: "dots",
        color: "#ffffff",
        birthRate: 0,
        maxSize: 0,
        minSize: 0,
        maxOpacity: 1,
        minOpacity: 0,
      },
      youTubeCta: {
        enabled: false,
        cornerPosition: "bottom-right",
      },
      emojiImages: [],
    },
    export: {
      format: "mp4",
      width: DEFAULT_EXPORT_DIMENSIONS.width,
      height: DEFAULT_EXPORT_DIMENSIONS.height,
      fps: DEFAULT_FRAME_RATE,
      videoBitrateKbps: null,
      audioBitrateKbps: null,
    },
    source: {
      legacyPresetId: null,
      legacyPresetVersion: null,
      legacyAspectRatioCode: null,
    },
    ...overrides,
  };
}
